name: infrastructure-foodyfood-prod
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - infra/environments/foodyfood-prod/foodyfood-prod.tfvars
  pull_request:
    branches:
      - master
    paths:
      - infra/environments/foodyfood-prod/foodyfood-prod.tfvars

jobs:
  terraform:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: infrastructure

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Format
      id: fmt
      run: terraform -chdir="./infra/manifests" fmt -check -recursive

    - name: Terraform Init
      id: init
      run: terraform -chdir="./infra/manifests" init -backend-config="../../environments/foodyfood-prod/foodyfood-prod.backend.tfvars" -reconfigure

    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      env:
        TF_VAR_linode_api_token: ${{ secrets.LINODE_API_TOKEN }}
        TF_VAR_godaddy_key: ${{ secrets.GODADDY_KEY }}
        TF_VAR_godaddy_secret: ${{ secrets.GODADDY_SECRET }}
      run: terraform -chdir="./infra/manifests" plan -var-file="../../environments/foodyfood-prod/foodyfood-prod.tfvars" -no-color
      continue-on-error: true

    - name: Update Pull Request
      uses: actions/github-script@v4.0.2
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          <details><summary>Show Plan</summary>
          \`\`\`${process.env.PLAN}\`\`\`
          </details>
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      env:
        TF_VAR_linode_api_token: ${{ secrets.LINODE_API_TOKEN }}
      run: terraform -chdir="./infra/manifests" apply -var-file="../../environments/foodyfood-prod/foodyfood-prod.tfvars" -auto-approve

    - name: Push tfstate To Repo
      if: github.ref == 'refs/heads/master' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Updating tfstate for foodyfood-prod'
        force-add: 'false'
        name: tf-github-action
        email: d1@outlook.ie
